# [概要] ワークフローファイルの構文チェックを行う
name: Action lint
on:
  # 動作確認しやすいように手動起動をサポート
  workflow_dispatch:
  pull_request:
    paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml']
permissions: {}
# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash
# ワークフローが複数起動したら自動キャンセル
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      # Bashトレーシングオプションの有効化でログを詳細化
      - name: Run actionlint
        run: |
          set -x
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:1.7.3